# These are supported funding model platforms

github: [osgeo,osm-in]
open_collective: amche-atlas
liberapay: # Replace with a single Liberapay username
thanks_dev: # Replace with a single thanks.dev username
custom: ['https://goafoundation.org']
